vich_uploader:
    db_driver: orm

    mappings:
        publications:
            uri_prefix: /images/publications
            upload_destination: '%kernel.project_dir%/public/images/publications'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
